'use strict';
let sampleClipboard=null;
function editAvailable(){if(!ready||recorder||importing||pending){say('Finish loading, recording or importing first.');return false}return true}
function stopPadVoices(keys){for(const source of voices)if(keys.includes(source.padKey)){try{source.stop()}catch{}source.cancelFlash?.()}}
function snapshotSampleEdit(){undo={full:true,samples:Object.fromEntries(Object.entries(p.samples).map(([key,sample])=>[key,{...sample}])),buffers:{...buffers},pattern:p.pattern.map(row=>[...row]),freeNotes:(p.freeNotes||[]).map(note=>({...note}))};$('undo').disabled=false}
function restoreSampleEdit(){if(!editAvailable())return;stopPadVoices([...letters]);p.samples=undo.samples;p.pattern=undo.pattern;p.freeNotes=undo.freeNotes;for(const key of Object.keys(buffers))delete buffers[key];Object.assign(buffers,undo.buffers);for(const key of Object.keys(reversed))delete reversed[key];undo=null;$('undo').disabled=true;resetDelete();save();render();say('Sample edit undone.')}
function copySample(key){if(!editAvailable())return false;const sample=p.samples[key];if(!sample){say(key+' is empty.');return false}sampleClipboard={key,sample:{...sample},buffer:buffers[key]};$('clipboardStatus').textContent=key+' copied · choose To, then Paste.';say(key+' copied.');return true}
function pasteSample(target){if(!editAvailable()||!sampleClipboard||!letters.includes(target)||target.length!==1)return false;if(p.samples[target]&&!confirm('Replace the sample on '+target+'? Undo can restore it.'))return false;snapshotSampleEdit();stopPadVoices([target]);p.samples[target]={...sampleClipboard.sample};delete buffers[target];if(sampleClipboard.buffer)buffers[target]=sampleClipboard.buffer;delete reversed[target];selected=target;save();render();$('clipboardStatus').textContent='Pasted to '+target+' · Undo available.';return true}
function moveSample(source,target){if(!editAvailable()||source===target||!p.samples[source]||!letters.includes(target)||target.length!==1)return false;if(p.samples[target]&&!confirm('Replace '+target+' and move '+source+' with its pattern notes? Undo can restore both.'))return false;snapshotSampleEdit();stopPadVoices([source,target]);p.samples[target]=p.samples[source];delete p.samples[source];delete buffers[target];if(buffers[source])buffers[target]=buffers[source];delete buffers[source];delete reversed[source];delete reversed[target];p.pattern=p.pattern.map(row=>[...new Set(row.map(key=>key===source?target:key))]);p.freeNotes=(p.freeNotes||[]).map(note=>note.key===source?{...note,key:target}:note);multiSelected.delete(source);selected=target;save();render();$('clipboardStatus').textContent=source+' moved to '+target+' with its notes · Undo available.';return true}
function clearSamplePattern(key){if(!editAvailable())return false;const exists=p.pattern.some(row=>row.includes(key))||(p.freeNotes||[]).some(note=>note.key===key);if(!exists){$('clipboardStatus').textContent=key+' has no pattern notes.';return false}snapshotSampleEdit();stopPadVoices([key]);p.pattern=p.pattern.map(row=>row.filter(k=>k!==key));p.freeNotes=(p.freeNotes||[]).filter(note=>note.key!==key);save();render();$('clipboardStatus').textContent=key+' removed from pattern · sample kept · Undo available.';return true}
for(const key of letters){$('manageSource').add(new Option(key,key));$('manageTarget').add(new Option(key,key))}
$('manageOpen').onclick=()=>{if(!editAvailable())return;$('manageSource').value=selected;$('manageTarget').value=[...letters].find(key=>!p.samples[key]&&key!==selected)||selected;$('clipboardStatus').textContent=sampleClipboard?sampleClipboard.key+' copied · ready to paste.':'Choose From and To. Empty destinations need no confirmation.';$('manageDialog').showModal()};
$('copySample').onclick=()=>copySample($('manageSource').value);
$('pasteSample').onclick=()=>pasteSample($('manageTarget').value);
$('moveSample').onclick=()=>moveSample($('manageSource').value,$('manageTarget').value);
$('clearSamplePattern').onclick=()=>clearSamplePattern($('manageSource').value);
$('manageClose').onclick=()=>$('manageDialog').close();
$('selectAllSteps').onclick=()=>{chosen.clear();for(let step=0;step<p.length;step++)chosen.add(step);renderSteps();say('All '+p.length+' active steps selected across all pages.')};
$('themeMode').value=themeChoice;$('themeMode').onchange=()=>setTheme($('themeMode').value);
if(!mobileUI){$('selectAllSteps').textContent='all steps [shift+\\]';$('themeMode').title='Theme [shift+,]'}
