const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
class El{set id(value){this._id=value;els[value]=this}get id(){return this._id}constructor(){this.children=[];this.dataset={};this.value='';this.checked=false;this.classList={add(){},remove(){},toggle(){}}}append(e){this.children.push(e)}add(){}set innerHTML(v){}querySelector(){return this.child??=new El()}setAttribute(k,v){this[k]=v}setPointerCapture(){}focus(){}select(){}click(){if(!this.disabled){this.checked=!this.checked;return this.onclick?.({detail:0})}}showModal(){this.open=true}close(){this.open=false}}
const els={},events={},timers=[];const sandbox={console,Blob,URL,URLSearchParams,Date,Option:class{},Float32Array,Uint8Array,ArrayBuffer,DataView,document:{documentElement:{dataset:{mobile:'true'}},getElementById:id=>els[id]??=new El(),createElement:()=>new El(),addEventListener(){}},window:{addEventListener:(n,fn)=>events[n]=fn},indexedDB:{open:()=>({})},setTimeout:(fn,ms)=>{const t={fn,ms};timers.push(t);return t},clearTimeout:t=>{if(t)t.cancelled=true},setInterval:()=>1,clearInterval(){}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('sampler.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('controls.js','utf8'),sandbox);
(async()=>{await vm.runInContext(`(async()=>{
ready=true;audio=async()=>{};const originalStart=startRecording,originalFinish=finishRecording;let started=0,finished=0;
startRecording=async(k,mode)=>{started++;recordKey=k;recorder={key:k,mode}};finishRecording=()=>{finished++;recordKey=null;recorder=null};
const q=$('keyboard').children[0].children[0],w=$('keyboard').children[0].children[1];const ev=(pointerId,timeStamp)=>({pointerId,timeStamp,button:0,pointerType:'touch',preventDefault(){}});
await q.onpointerdown(ev(1,0));q.onpointerup(ev(1,100));if(started!==1||finished!==0)throw Error('short tap did not latch');await q.onclick({detail:1});if(started!==1)throw Error('duplicate compatibility click');await q.onpointerdown(ev(2,200));q.onpointerup(ev(2,240));if(finished!==1)throw Error('second tap did not finish');
await q.onpointerdown(ev(3,300));q.onpointerup(ev(3,800));if(started!==2||finished!==2)throw Error('hold did not record and release');
$('thresholdOn').checked=true;await q.onpointerdown(ev(4,900));q.onpointerup(ev(4,1400));if(finished!==3)throw Error('threshold hold did not finish');
let hits=[];trigger=k=>hits.push(k);p.samples.Q={name:'Q',gain:1,start:0,end:1,blob:new Blob(['q'])};p.samples.W={name:'W',gain:1,start:0,end:1,blob:new Blob(['w'])};buffers.Q={duration:1};buffers.W={duration:1};ctx={currentTime:0};
await q.onpointerdown(ev(5,1500));await w.onpointerdown(ev(6,1500));if(hits.join('')!=='QW'||multiSelected.size!==2)throw Error('multi-touch selection/playback');q.onpointerup(ev(5,1600));w.onpointerup(ev(6,1600));
$('deleteMode').click();await activatePad('Q');if(!p.samples.Q||!deleteSelection.has('Q'))throw Error('first delete tap removed sample');await activatePad('Q');if(!p.samples.Q||deleteSelection.size!==0||$('deleteMode').textContent!=='cancel delete')throw Error('deselect failed');await activatePad('Q');if($('deleteMode').textContent!=='delete (1)')throw Error('delete confirmation label');toggleDelete();if(p.samples.Q)throw Error('Delete button did not confirm');$('undo').click();if(!p.samples.Q)throw Error('single undo failed');
toggleDelete();await activatePad('Q');await activatePad('W');if(deleteSelection.size!==2||!p.samples.Q)throw Error('bulk selection');toggleDelete();if(p.samples.Q||p.samples.W)throw Error('bulk delete');$('undo').click();if(!p.samples.Q||!p.samples.W)throw Error('bulk undo');
playing=true;nextStep=7;$('bpm').value=140;$('bpm').onchange();if(!playing||p.bpm!==140)throw Error('tempo stopped playback');$('length').value=4;$('length').onchange();if(!playing||nextStep!==3)throw Error('length stopped/reset');$('division').value=.25;$('division').onchange();if(!playing||p.division!==.25)throw Error('division stopped');playing=false;
multiSelected.clear();multiSelected.add('Q');multiSelected.add('W');$('fxOpen').click();$('fxPitch').value=12;$('fxCutoff').value=8000;$('fxPan').value=-.5;$('fxApply').click();if(p.samples.Q.pitch!==12||p.samples.W.cutoff!==8000)throw Error('FX multi apply');
startRecording=originalStart;finishRecording=originalFinish;
})()`,sandbox);
const triggerSource=fs.readFileSync('sampler.js','utf8').split('function trigger(')[1].split('function click(')[0];vm.runInContext('trigger=function trigger('+triggerSource,sandbox);
await vm.runInContext(`(()=>{let filters=0,panners=0;const nodes=[];const node=()=>{const n={connections:[],playbackRate:{value:1},gain:{value:1},connect(to){this.connections.push(to);return to},disconnect(){},start(){}};nodes.push(n);return n};ctx={currentTime:0,createBufferSource:node,createGain:node,createBiquadFilter(){filters++;return {...node(),frequency:{}}},createStereoPanner(){panners++;return {...node(),pan:{}}}};master={};p.samples.Q={gain:1,start:0,end:1};buffers.Q={duration:1};trigger('Q');if(filters||panners||nodes[0].connections[0]!==nodes[1]||nodes[1].gain.value!==1)throw Error('default signal path changed');})()`,sandbox);
let asks=0;const track={readyState:'live',stop(){this.readyState='ended'}};sandbox.navigator={audioSession:{type:'auto'},mediaDevices:{getUserMedia:async()=>{asks++;return {getAudioTracks:()=>[track],getTracks:()=>[track]}}}};await vm.runInContext('Promise.all([requestMicrophone(),requestMicrophone()])',sandbox);assert.equal(asks,1);await vm.runInContext('requestMicrophone()',sandbox);assert.equal(asks,1);assert.equal(sandbox.navigator.audioSession.type,'play-and-record');await vm.runInContext('releaseMicrophone()',sandbox);assert.equal(track.readyState,'ended');assert.equal(sandbox.navigator.audioSession.type,'playback');
console.log('PASS: immediate tap recording, tap finish, hold/release, threshold release, duplicate click suppression, multi-selection, confirmed deletion, bulk undo, live tempo/length/division, shared FX, microphone request reuse, track release, playback-session restoration, unprocessed default audio path.');})();
